### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by sparxHub** [node-inspector/v8-debug#7]
I am getting below error while installing v8-debug, any ideas?

1035 info install v8-debug@0.3.1
1036 verbose unsafe-perm in lifecycle true
1037 info v8-debug@0.3.1 Failed to exec install script
1038 verbose unlock done using C:\Users\Nadav\AppData\Roaming\npm-cache_locks\v8-debug-6a84c2f0ebeb5635.lock for C:\Program Files\nodejs\node_modules\v8-debug
1039 verbose stack Error: v8-debug@0.3.1 install: `node-pre-gyp install --fallback-to-build`
1039 verbose stack Exit status 1
1039 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:212:16)
1039 verbose stack     at EventEmitter.emit (events.js:98:17)
1039 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
1039 verbose stack     at ChildProcess.emit (events.js:98:17)
1039 verbose stack     at maybeClose (child_process.js:766:16)
1039 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
1040 verbose pkgid v8-debug@0.3.1
1041 verbose cwd C:\Program Files\nodejs
1042 error Windows_NT 6.2.9200
1043 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "v8-debug"
1044 error node v0.10.34
1045 error npm  v2.1.16
1046 error code ELIFECYCLE
1047 error v8-debug@0.3.1 install: `node-pre-gyp install --fallback-to-build`
1047 error Exit status 1
1048 error Failed at the v8-debug@0.3.1 install script 'node-pre-gyp install --fallback-to-build'.
1048 error This is most likely a problem with the v8-debug package,
1048 error not with npm itself.
1048 error Tell the author that this fails on your system:
1048 error     node-pre-gyp install --fallback-to-build
1048 error You can get their info via:
1048 error     npm owner ls v8-debug
1048 error There is likely additional logging output above.
1049 verbose exit [ 1, true ]
1050 verbose unbuild node_modules\v8-debug

**Comment by ericchaves** [comment]
I'm facing the same trouble. @SparkGithub could you share the steps you did to solve it?

**Comment by 3y3** [comment]
I added some fixes to v8-profiler and v8-debug. Also I added prebuild binaries for Linux and OSX.
Please try to reinstall node-inspector now.

**Comment by afreeland** [comment]
I am having this issue as well

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector
"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.3.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.3.5 install script 'node-pre-gyp install --fal
lback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
```

I appear to be having a similar issue...any udpates?

**Comment by CoreSoft2** [comment]
Same issue here

pm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.10.21
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by p1tt1** [comment]
Same issue here

**Comment by lhttjdr** [comment]
Same issue with v8-debug@0.4.6

**Comment by pjcliche** [comment]
Same problem, but running on Debian. Here's the actual erroring out leading to the failure message :

  CXX(target) Release/obj.target/debug/src/debug.o
In file included from ../src/debug.cc:2:0:
../node_modules/nan/nan.h:261:25: error: redefinition of 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)' previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: 'node::smalloc' has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ',' or '...' before 'callback'
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)':
../node_modules/nan/nan.h:665:50: error: 'callback' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: 'hint' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)':
../node_modules/nan/nan.h:672:67: error: call of overloaded 'New(v8::Isolate*, const char*&, uint32_t&)' is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/debug.cc:2:
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from 'uint32_t {aka unsigned int}' to 'node::encoding'
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from 'const char*' to 'char*'
In file included from ../src/debug.cc:2:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(uint32_t)':
../node_modules/nan/nan.h:676:61: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))' from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanBufferUse(char*, uint32_t)':
../node_modules/nan/nan.h:683:12: error: 'Use' is not a member of 'node::Buffer'
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/debug.cc: In static member function 'static void nodex::Debug::InternalConstructorName(const v8::FunctionCallbackInfo<v8::Value>&)':
../src/debug.cc:194:23: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
           result_type = "";
                       ^
debug.target.mk:90: recipe for target 'Release/obj.target/debug/src/debug.o' failed
make: *** [Release/obj.target/debug/src/debug.o] Error 1

**Comment by wpm** [comment]
I'm seeing the same thing when I try to build the default Yeoman [angular-fullstack](https://github.com/DaftMonk/generator-angular-fullstack).

```
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/Users/williammcneill/Documents/Work/QA/devenv/src/cloudhammer/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/Users/williammcneill/Documents/Work/QA/devenv/src/cloudhammer/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/williammcneill/Documents/Work/QA/devenv/src/cloudhammer/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/4.1.0/bin/node" "/Users/williammcneill/Documents/Work/QA/devenv/src/cloudhammer/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/williammcneill/Documents/Work/QA/devenv/src/cloudhammer/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
```

*node-pre-gyp 0.6.10, Node 4.1.0, OS X 10.10.5*

**Comment by jamescalhoun** [comment]
I also am seeing this issue when I try to run npm install using Yeoman angular-fullstack 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build

**Comment by 3y3** [comment]
The problem is in grunt-node-inspector, which was linked to outdated node-inspector version.
Can anyone call `grunt-node-inspector` maintainer to approve on a pr which bumps `node-inspector` version?

**Comment by remydavid** [comment]
Same problem for me, solved by npm install -g grunt-node-inspector, which installs the latest version (0.3.0) which doesn't seems to have the problem.

**Comment by sonidodespacio** [comment]
I have the same problem running:
```
 yo meanjs
```

**Comment by hanssl** [comment]
I am getting the same "Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'." error.  I have tried rolling npm back to v2, that did not fix it.  I have tried the suggestion above 'npm install -g grunt-node-inspector' but that did not fix the issue.

**Comment by 3y3** [comment]
@hanssl ,
`grunt-node-inspector` already updated and uses correct v8-debug version. Where you found outdated `grunt-node-inspector`?

Maybe `npm cache clean` will be helpful for you?

**Comment by hanssl** [comment]
I have tried ‘npm cache clean’ with ‘bower cache clean’ many times.  Problem persists.

I have attached my npm log.

**Comment by fcagalj** [comment]
Does this have any sense: "opened this issue on Dec 25, 2014"????

I leave Windows hoping to avoid this issues, after spending ages on node-gyp nonsenses. 

So now I need to spend week to make PR to grunt-node-inspector and hope somebody will accept in order to use it until next bug appear?

**Comment by sdoushi1** [comment]
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-node-inspector"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.5.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.5.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

Same issue here, I'm running ubuntu.

**Comment by fcagalj** [comment]
Rollback to node 4.2.2 solved problems for me on Ubuntu 14.04.

**Comment by yves-s** [comment]
I was on node 5, rolled back to node 4.2.2 but still the same error. I'm on OSx 10.11.

In my case the issue happens with angular-fullstack as well or rather `npm install`

Any new insights?

**Comment by russfrisch** [comment]
I was experiencing this same issue. Changing in the version for grunt-node-inspector to prepend a ">=" instead of a "~" got this to work for me.

**Comment by stephen-cernota** [comment]
@russfrisch +1 worked for me

**Comment by yves-s** [comment]
@russfrisch worked for me as well, thx

**Comment by marfago** [comment]
@russfrisch  worked for me as well on Node 0.12.7. Thank you.

**Comment by surprisetalk** [comment]
I encountered the same problem when trying to install meanjs with nodejs@4.2.2 and npm@2.14.10. Going into the package.json (in the cloned meanjs repo) and changing 

> "grunt-node-inspector": "~0.2.0" 

to

> "grunt-node-inspector": ">=0.2.0",

did the trick.

Thanks @russfrisch !

**Comment by srabeeh** [comment]
Thanks @russfrisch

**Comment by dam1** [comment]
You can also update the package.json to

        "grunt-node-inspector": "^0.4.1",

**Comment by tgwhite** [comment]
Was having same error on windows *and* ubuntu after I rage-quit windows. Also using the angular-fullstack generator. @russfrisch fix worked like a charm in ubuntu 14.04 -- will report back if it works in windows.

**Comment by adityareddy** [comment]
+1 Thanks @russfrisch

**Comment by g1eb** [comment]
@russfrisch +1

**Comment by lazaropj** [comment]
@russfrisch +1

**Comment by bownie** [comment]
Wow @russfrisch +1 - indeed this also works for Windows.  Also had this problem using the angular fullstack generator and originally came via this issue https://github.com/nodejs/node-gyp/issues/629

**Comment by jakejooyoung** [comment]
@russfrisch +1

**Comment by jackkum** [comment]
@surprisetalk :+1:

**Comment by RGFnaGFuIEd1bmF5** [comment]
@russfrisch +1

**Comment by FingersCrossed** [comment]
@russfrisch +1

**Comment by bastianwegge** [comment]
@russfrisch +1 !!!

**Comment by jquigley1003** [comment]
Thanks for your solution @russfrisch +1 !!!

**Comment by ryanooi** [comment]
@russfrisch +1

**Comment by fdfandrade** [comment]
@russfrisch Thanks!

**Comment by Aabir1** [comment]
i am not able to use this
 => sudo yo meanjs:crud-module costomers. 
please help me . i am stuck from yesturday

**Comment by surprisetalk** [comment]
@Aabir1 
I think `meanjs:crud-module` has been removed from the newer version of Yo. 
Use `yo --help` and then see if it appears under "Available Generators".
I know `sudo yo meanjs:mean-module customers` will work, but it will not do quite what `meanjs:crud-module` used to do.
Best of luck.

**Comment by creepy00** [comment]
@russfrisch +1 Thanks :)

**Comment by colwilson** [comment]
Thanks @russfrisch that fixed it for me +1

**Comment by burakkilic** [comment]
+1 @russfrisch thank you

**Comment by SHEFFKUAN** [comment]
Can anyone tell me where can i find that package.json, which package.json. @burakkilic

**Comment by kinzhao** [comment]
@SHEFFKUAN it should be located where you root directory is. Example: project_folder/package.json

**Comment by kannach** [comment]
@russfrisch +1

**Comment by chusri** [comment]
@russfrisch +1 it's work

**Comment by hsgfan** [comment]
+1

**Comment by colkito** [comment]
@russfrisch Thanks! it's work!

**Comment by TanyongTh** [comment]
@russfrisch Thank you. It's work for me

**Comment by nibaer** [comment]
@russfrisch thx.

**Comment by FFultimo** [comment]
+1

**Comment by Ankur-Marwaha** [comment]
Can some one tell me how can i change the globaly installed grunt-node-inspector from this version 3.6.0 to "grunt-node-inspector": ">=0.2.0"  ?

**Comment by antharamshivakumar** [comment]
can someone help me in removing these errors ?

I tried npm cache clean but it didn't work for me.

Please find the attachment.
![capture](https://cloud.githubusercontent.com/assets/21262011/19806698/2ef20e5c-9d3a-11e6-88f8-8d4d6fedd8e9.PNG)

**Comment by rattrayalex** [comment]
Using `node --inspect` instead has worked for me as a replacement. Uses node's builtin inspector instead. Node v6.3 or greater.

**Comment by antharamshivakumar** [comment]
![capture](https://cloud.githubusercontent.com/assets/21262011/19901640/ffe2d6da-a024-11e6-928c-557f3c7ba55b.PNG)

**Comment by antharamshivakumar** [comment]
![capture2](https://cloud.githubusercontent.com/assets/21262011/19901739/6085e9c8-a025-11e6-87f7-17a025bbadd5.PNG)

**Comment by antharamshivakumar** [comment]
i am new to nodejs where i have to inspect?

**Comment by antharamshivakumar** [comment]
thanks@rattrayalex

I used  npm install -g node-gyp and it worked for me.

**Comment by drewpc** [comment]
Recommend avoiding node-inspector altogether until this is fixed.  Here's the cause of v8-debug failing to install:

- In May of 2015, the nodejs project updated their header files with the latest from Google's V8 project.  You can see here that Google deprecated the function call for `Call()` (and others): https://github.com/nodejs/node/blame/master/deps/v8/include/v8-debug.h#L198
- In Sep of 2016, nodejs removed the old `Call()` when importing the V8 version 5.4.500.27.
- The v8-debug project hasn't kept pace with the functions defined in `v8-debug.h`, so the function calls v8-debug uses doesn't exist in the newer versions of nodejs--hence the failing builds.  See the function call here: https://github.com/node-inspector/v8-debug/blob/master/src/debug.cc#L38

Unfortunately, I don't have the time/knowledge to update `debug.cc` and fix this, but hopefully someone else can update that file to match the appropriate headers depending on the version of node.

This also applies to the following open issue: #26, #28, and #30.

**Comment by singsai** [comment]
I was finally able to successfully install **node-inspector** by switching to Node v6.5.0

If you using **n** [https://github.com/tj/n](url) you can do:
`sudo n 6.5.0`
Then, this should finally work: 
`npm install -g node-inspector`

**Comment by dcpartners** [comment]
As per @singsai , we did below instead and run npm install node-inspector works well.
`sudo n 6.10.0`

**Comment by huazi103** [comment]
gyp support python2.X，not python3. so if you use python3, change to python 2.X, ( 2.X >= 2.5 ), and set the enviroment path for python 2.X

**Comment by hatinfotech** [comment]
I was resolved my problem by install package in native console, install via ssh terminal was not wokrked.

**Comment by alarv** [comment]
Downgrading node to ```v6.9.1``` worked for me

**Comment by shivarajnaidu** [comment]
Any Other Solution ?? I Want to install for Node v8.x

**Comment by ashishyadav23** [comment]
thanks @russfrisch +1 its work for me also

**Comment by chucklu** [comment]
After checking the FAQ of node-pre-gyp, I might need to install the C++ runtime. I am installing it now and give feedback here tomorrow.
[Frequently Ask Questions about node-pre-gyp](https://github.com/mapbox/node-pre-gyp/wiki/FAQ)
On Windows for Node C++ modules that do not link external libraries there are no major gotchas. The binaries you build will work well on any Windows system. This is because the default linking for Node is /MT (aka RuntimeLibrary:0) and node-pre-gyp modules inherit this setting by default. So, the C++ runtime will be statically linked into the addon binary and therefore you don't need to worry about your users installing it separately.

However, for Node C++ modules on Windows that depend on external shared libraries, you'll need to understand whether those libraries were linked with /MD or /MT. If the external DLL was linked with /MD then you'll likely need to also link your Node C++ addon using /MD and you'll need to ensure that your users have the right C++ runtime installed for your addon binary to work. For example, if you compiled your binary with Visual Studio 2013 then your users would need This "C++ Redistributable".

**Comment by chucklu** [comment]
I am not sure why the proxy is invalid, I already configured the proxy as https://stackoverflow.com/questions/40171953/node-npm-proxy-authentication-how-do-i-configure-it. It's just a warning.
And the error is :
```
Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-win32-x64.tar.gz
 node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@10.2.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
```
Anyone knows something about this? @russfrisch 

> C:\Users\clu\AppData\Roaming\npm\node-inspector -> C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\bin\inspector.js
> C:\Users\clu\AppData\Roaming\npm\node-debug -> C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\bin\node-debug.js
> 
> > v8-debug@1.0.1 install C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp WARN download ignoring invalid "proxy" config setting: "sasygsha01prx11_p.asnet.services.net:8080"
> node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-win32-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for v8-debug@1.0.1 and node@10.2.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: unable to get local issuer certificate
> gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
> gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
> gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:635:8)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\clu\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v64-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\clu\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v1.0.1\\node-v64-win32-x64" "--python=C:\\Users\\clu\\.windows-build-tools\\python27" "--msvs_version=2015"
> gyp ERR! cwd C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> gyp ERR! node -v v10.2.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64\debug.node --module_name=debug --module_path=C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64 --python=C:\Users\clu\.windows-build-tools\python27 --msvs_version=2015' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
> node-pre-gyp ERR! System Windows_NT 10.0.16299
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\clu\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp ERR! node -v v10.2.1
> node-pre-gyp ERR! node-pre-gyp -v v0.6.39
> node-pre-gyp ERR! not ok
> Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64\debug.node --module_name=debug --module_path=C:\Users\clu\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug\build\debug\v1.0.1\node-v64-win32-x64 --python=C:\Users\clu\.windows-build-tools\python27 --msvs_version=2015' (1)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! v8-debug@1.0.1 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the v8-debug@1.0.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\clu\AppData\Roaming\npm-cache\_logs\2018-05-28T13_47_32_913Z-debug.log

**Comment by chucklu** [comment]
> node-pre-gyp ERR! Tried to download(undefined): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v64-win32-x64.tar.gz

Someone has submit an issue in node-inspector already
https://github.com/node-inspector/node-inspector/issues/1041

**Comment by zhaoyongjiang** [comment]
@antharamshivakumar  Is the problem solved? My computer is the macmini。I need your help。thanks a lot

**Comment by chucklu** [comment]
@zhaoyongjiang  No, I gave up. And I find the following message for node-inspector

> Since version 6.3, Node.js provides a built-in DevTools-based debugger which mostly deprecates Node Inspector, see e.g. this blog post to get started. The built-in debugger is developed directly by the V8/Chromium team and provides certain advanced features (e.g. long/async stack traces) that are too difficult to implement in Node Inspector.

I  decide  to use the built-in debugger in Node.js .

**Comment by smdpro** [comment]
@russfrisch +1 worked for me

**Comment by zhaoyongjiang** [comment]
@chucklu thanks a lot

**Comment by tommyyama2020** [comment]
anybody encountering the same in the latest ubuntu ? i changed to ">=" as suggested here. But it failed.

**Comment by kenliten** [comment]
I'm on OpenSUSE and for me, nothing here is working.

I'm having the same error and the same with Linux mint, anyone knows another way to make it works?
